name: epair_files

on:
  schedule:
    - cron: '0 11 * * 1'


  workflow_dispatch:


jobs: 
  check:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-r@master
    
    - name: Rpackages
      run: |
        R -e 'install.packages("memoise")'
        R -e 'install.packages("stringr")'
        R -e 'install.packages("httr")'
        R -e 'install.packages("R.cache")'
        R -e 'install.packages("testthat")'
        R -e 'install.packages("remotes")'
        R -e 'install.packages("stringi")'  

    
    - name: livecheck
      env: 
            API_KEY: ${{secrets.API_KEY}}
            API_EMAIL: ${{secrets.API_EMAIL}}
      run: Rscript "tests/testthat/live_test_setup.R"
